influxdb:
  image: influxdb:1.8.4
  container_name: influxdb
  restart: always
#  mem_limit: 192m
  ports:
   - "8086:8086"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    - ./influxdb/data:/var/lib/influxdb
    # Configuration
    - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro

telegraf:
  image: telegraf:latest
  container_name: telegraf
  restart: always
  environment:
   - HOST_PROC=/host/proc
  privileged: true
#  mem_limit: 384m
  ports:
    # Expose Statsd UDP server to local host
    - "8125:8125/udp"
  links:
    - influxdb
  volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /proc:/host/proc:ro
    - /var/log:/host/var/log:ro
